### ISSUE TITLE
About conf files and an error

### ISSUE THREAD

**Issue by chaufanglin** [sungnyun/avsr-temporal-dynamics#1]
Hi Sungnyun,

Thanks for sharing the code. I found the conf files are not provided, do you use the same conf file as in AV-HuBERT? 
I tried using the avhubert conf file and changed the model name to xmodal_av_hubert_seq2seq. It showed this error:

> File "avsr-temporal-dynamics/avhubert/hubert.py", line 769, in extract_finetune_features
> assert 'clean_audio' in source
> AssertionError

Many thanks,
Zhaofeng

**Comment by sungnyun** [comment]
Hi Zhaofeng,

Sorry for inconvenience. I just uploaded the missing config file [here](https://github.com/sungnyun/avsr-temporal-dynamics/blob/main/avhubert/conf/av-finetune/large_noise_pt_noise_ft_433h_xmodal.yaml).
Please use this one.

Thanks,
Sungnyun Kim

**Comment by chaufanglin** [comment]
Thank you for your quick response!

The model name in the config file didn't work initially, but I was able to resolve the issue by changing it to `xmodal_av_hubert_seq2seq`. I appreciate your help!

Many thanks,
Zhaofeng

**Comment by sungnyun** [comment]
My bad, you are right. I appreciate it!
